version: '3'

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"

  api:
    depends_on:
      - db
    image: semrekkers/caps-api:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      MONGO_URI: mongodb://db:27017/caps
      TLS: <YOUR_EMAIL>
      HOSTNAME: <YOUR_HOSTNAME>
      JWT_SECRET: <YOUR_SECRET>